// ── INICIO: lista_centros_galicia ────────────────────
// Lista oficial de centros educativos de Galicia
// Fonte: Consellería de Educación, Xunta de Galicia
export const CENTROS_GALICIA = [
  // ── A Coruña ─────────────────────────────────────────
  'IES Agra do Orzán (A Coruña)',
  'IES Anxel Fole (A Coruña)',
  'IES Breamo (Pontedeume)',
  'IES Cabo Ortegal (Cariño)',
  'IES Calvo Sotelo (A Coruña)',
  'IES Canido (Ferrol)',
  'IES Carballo',
  'IES Cacheiras (Teo)',
  'IES Chorente (Ortigueira)',
  'IES Concepción Arenal (Ferrol)',
  'IES David Buján (Cambre)',
  'IES Eusebio da Guarda (A Coruña)',
  'IES Ferrol Vello (Ferrol)',
  'IES Fin do Camiño (Finisterre)',
  'IES Frián-Teis (Vigo)',
  'IES Lamas de Abade (Santiago de Compostela)',
  'IES Maximino Romero de Lema (Baio)',
  'IES Melide',
  'IES Monte Neme (Carballo)',
  'IES Monelos (A Coruña)',
  'IES Mugardos',
  'IES Noia',
  'IES Número 1 (Ribeira)',
  'IES Obradoiro (Santiago de Compostela)',
  'IES Ollos Grandes (Lugo)',
  'IES Ortigueira',
  'IES Pazo da Mercé (As Neves)',
  'IES Pedra da Auga (Ponteareas)',
  'IES Plurilingüe Aquis Querquennis (Bande)',
  'IES Plurilingüe de Cacheiras (Teo)',
  'IES Plurilingüe Fontexería (Muros)',
  'IES Plurilingüe Indalecio Pérez Tizón (Ordes)',
  'IES Plurilingüe Rosalía de Castro (Santiago de Compostela)',
  'IES Poeta Añón (Outes)',
  'IES Ponteceso',
  'IES Porto do Son',
  'IES Ramón Cabanillas (Cambados)',
  'IES Rosalía de Castro (Santiago de Compostela)',
  'IES Salvador de Madariaga (A Coruña)',
  'IES San Clemente (Santiago de Compostela)',
  'IES San Paio (Tui)',
  'IES Santiago de Compostela',
  'IES Sofía Casanova (A Coruña)',
  'IES Urbano Lugrís (A Coruña)',
  'IES Val do Asma (Chantada)',
  'IES Xelmírez I (Santiago de Compostela)',
  'IES Xelmírez II (Santiago de Compostela)',
  'IES Xograr Afonso Gómez (Sarria)',

  // ── Lugo ─────────────────────────────────────────────
  'IES A Pinguela (Monforte de Lemos)',
  'IES A Pontepedriña (Lugo)',
  'IES Anxo Fole (Lugo)',
  'IES Basanta Silva (Vilalba)',
  'IES Castelao (Vigo)',
  'IES Castro Alobre (Vilagarcía de Arousa)',
  'IES Chapela (Redondela)',
  'IES Lois Peña Novo (Vilalba)',
  'IES Lucus Augusti (Lugo)',
  'IES Nosa Señora dos Ollos Grandes (Lugo)',
  'IES Outeiro de Rei',
  'IES Parga (Guitiriz)',
  'IES Pedregal de Irimia (Meira)',
  'IES Sanxillao (Lugo)',
  'IES Terra Chá (Castro de Rei)',
  'IES Urbano Lugrís (Lugo)',
  'IES Virxe do Cádavo (Baleira)',

  // ── Ourense ──────────────────────────────────────────
  'IES A Carballeira (Ourense)',
  'IES A Gudiña',
  'IES As Lagoas (Ourense)',
  'IES Blanco Amor (Ourense)',
  'IES Castro de Baronceli (Ribadavia)',
  'IES Chamoso Lamas (A Pobra de Trives)',
  'IES Cosme López Rodríguez (A Rúa)',
  'IES Frei Martín Sarmiento (Mondoñedo)',
  'IES Lauro Olmo (O Barco de Valdeorras)',
  'IES Otero Pedrayo (Ourense)',
  'IES Ramón Otero Pedrayo (Ourense)',
  'IES Río Cabe (Monforte de Lemos)',
  'IES Valle Inclán (Pontevedra)',
  'IES Xesús Taboada Chivite (Verín)',

  // ── Pontevedra ───────────────────────────────────────
  'IES A Basella (Vilanova de Arousa)',
  'IES A Illa de Arousa',
  'IES Aquis Querquennis (Bande)',
  'IES As Barxas (Moaña)',
  'IES Audiovisual (Vigo)',
  'IES Beade (Vigo)',
  'IES Belén (Vigo)',
  'IES Cabanas (Pontevedra)',
  'IES Camiño de Santiago (Pontevedra)',
  'IES Cans (O Porriño)',
  'IES Chan do Monte (Marín)',
  'IES Cidade de Antioquía (Xinzo de Limia)',
  'IES Cortegada (Vilagarcía de Arousa)',
  'IES Cuíña (Ponteareas)',
  'IES de Salvaterra de Miño',
  'IES Escolas Proval (Nigrán)',
  'IES Espiñeira (Boiro)',
  'IES Fernando Wirtz Suárez (Vigo)',
  'IES Fontexería (Muros)',
  'IES Illa de Tambo (Marín)',
  'IES Johan Carballeira (Bueu)',
  'IES Laxeiro (Lalín)',
  'IES Manuel Antonio (Vigo)',
  'IES Marco do Camballón (Vila de Cruces)',
  'IES María Soliña (Cangas)',
  'IES Mendiño (Redondela)',
  'IES Montecelo (Pontevedra)',
  'IES Mugardos (Ferrol)',
  'IES Navia (Vigo)',
  'IES Outeiro de Rei (Lugo)',
  'IES Pazo da Mercé (As Neves)',
  'IES Pedra da Auga (Ponteareas)',
  'IES Pintor Colmeiro (Silleda)',
  'IES Plurilingüe A Cachada (Boiro)',
  'IES Plurilingüe de Vilalonga (Sanxenxo)',
  'IES Plurilingüe Fontexería (Muros)',
  'IES Plurilingüe Mendiño (Redondela)',
  'IES Plurilingüe Urbano Lugrís (A Coruña)',
  'IES Pontecesures',
  'IES Porriño',
  'IES Ribeira do Louro (O Porriño)',
  'IES Ricardo Mella (Vigo)',
  'IES Rodeira (Cangas)',
  'IES San Paio (Tui)',
  'IES Sanxenxo',
  'IES Sárdoma (Vigo)',
  'IES Torrente Ballester (Pontevedra)',
  'IES Val Miñor (Nigrán)',
  'IES Valadares (Vigo)',
  'IES Valle Inclán (Pontevedra)',
  'IES Vilar de Barrio',
  'IES Xunqueira I (Pontevedra)',
  'IES Xunqueira II (Pontevedra)',

  // ── Universidades ────────────────────────────────────
  'Universidade de Santiago de Compostela (USC)',
  'Universidade da Coruña (UDC)',
  'Universidade de Vigo (UVigo)',

  // ── Formación Profesional ────────────────────────────
  'CIFP A Carballeira (Ourense)',
  'CIFP A Farixa (Ourense)',
  'CIFP Ánxel Casal - Monte Alto (A Coruña)',
  'CIFP As Mercedes (Lugo)',
  'CIFP Compostela (Santiago de Compostela)',
  'CIFP Coroso (Ribeira)',
  'CIFP Ferrolterra (Ferrol)',
  'CIFP Fontexería (Muros)',
  'CIFP Manuel Antonio (Vigo)',
  'CIFP Rodolfo Ucha Piñeiro (Ferrol)',
  'CIFP Valentín Paz Andrade (Vigo)',
  'CIFP Xelmírez I (Santiago de Compostela)',

  // ── Outros ───────────────────────────────────────────
  'Centro de Educación de Adultos (CEA)',
  'Escola Oficial de Idiomas (EOI)',
  'Outro centro educativo',
]
// ── FIN: lista_centros_galicia ───────────────────────

// ── INICIO: buscar_centros ───────────────────────────
export const buscarCentros = (query, max = 6) => {
  if (!query || query.length < 2) return []
  const q = query.toLowerCase()
  return CENTROS_GALICIA
    .filter(c => c.toLowerCase().includes(q))
    .slice(0, max)
}
// ── FIN: buscar_centros ──────────────────────────────